// Tailwind CSS Config - Extracted from i9fix.com.br
// Generated by DesignAssets

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        'dark-gray': {
          '800': '#333333',
          '900': '#202020',
          '900': '#121314',
        },
        'blue': {
          '300': '#6EC1E4',
          '400': '#1F95FF',
          '400': '#1FC3FF',
          '500': '#2D7ABF',
          '500': '#5F778B',
          '600': '#3F527A',
          '700': '#3F444B',
          '800': '#14334F',
        },
        'white': {
          '50': '#FFFFFF',
          '100': '#F1F1F1',
        },
        'light-gray': {
          '100': '#E1E8ED',
          '100': '#DDDDDD',
          '200': '#CCD6DF',
        },
        'black': '#000000',
        'green': {
          '600': '#29A251',
          '800': '#1A532D',
        },
        'red': '#CC3366',
        'purple': '#BFCDDA',
      },
      fontFamily: {
        'apple-system': ['"-apple-system"', 'sans-serif'],
        'inter': ['"Inter"', 'sans-serif'],
        'arial': ['"Arial"', 'sans-serif'],
        'times': ['"Times New Roman"', 'serif'],
        'gilroy': ['"Gilroy"', 'serif'],
      },
      fontSize: {
        '11': '11.05px',
        '13': '13px',
        '13': '13.6px',
        '14': '14px',
        '15': '15px',
        '16': '16px',
        '18': '18px',
        '20': '20px',
        '22': '22px',
        '24': '24px',
      },
      borderRadius: {
        'none': '999px',
        'sm': '100px',
        'md': '16px',
        'lg': '5px',
        'xl': '45px',
        '2xl': '3px',
      },
      boxShadow: {
        'sm': 'rgba(0, 0, 0, 0.05) 0px 0px 30px 0px',
        'DEFAULT': 'rgba(87, 248, 141, 0.18) 0px 0px 3.60981px 23.6828px',
        'md': 'rgba(0, 0, 0, 0.2) 0px 4px 8px 0px',
        'lg': 'rgba(87, 248, 141, 0.18) 0px 0px 3.60983px 23.6828px',
      },
    },
  },
  plugins: [],
}
